/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mfiari.pokemon.server.demarrage;

import mfiari.pokemon.core.capacite.Attributs;
import mfiari.pokemon.server.capacite.Capacites;
import mfiari.pokemon.core.capacite.Etat;
import mfiari.pokemon.core.list.ListeDeCapacite;

/**
 *
 * @author mike
 */
public class CreationCapacite {
    
    private final ListeDeCapacite listeDeCapacite = new ListeDeCapacite ();

    public CreationCapacite () {
        this.creeCapacite();
        this.listeDeCapacite.ajoutListeCapacite(Capacites.abime);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.abri);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.acidarmure);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.acide);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.adaptation);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.aeropique);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.amnesie);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.anneau_hydro);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.aqua_jet);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.armure);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.aromatherapi);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.assurance);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.attaque_brulante);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.atterrisage);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.avale);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.balayage);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.ball_Ombre);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.balle_graine);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.bec_vrille);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.belier);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.berceuse);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.blizzard);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.boul_armure);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.boule_roc);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.bourdon);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.brouillard);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.bulleDo);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.cage_eclair);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.charge);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.choc_mental);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.close_combat);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.combo_griffe);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.corps_perdu);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.coup_croix);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.coup_d_boul);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.coupdmain);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.croc_de_mort);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.croc_eclair);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.croc_fatal);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.croc_givre);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.crochetvenin);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.croissance);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.cru_aile);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.cyclone);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.damocles);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.danse_flamme);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.danse_fleur);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.danse_pluie);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.dard_nuee);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.dard_venin);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.deflagration);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.destruction);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.detricanon);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.detritus);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.direct_toxik);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.double_dard);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.double_pied);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.draco_rage);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.dracocharge);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.dynamopoing);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.e_coque);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.eboulement);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.eclair);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.eclategriffe);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.eclats_glace);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.eco_sphere);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.ecras_face);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.ecrasement);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.ecume);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.electacle);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.empal_korne);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.entrave);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.etreinte);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.explosion);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.fatal_foudre);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.feinte);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.feuillmagik);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.flammeche);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.force_poigne);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.fouet_liane);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.frappe_atlas);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.frenesie);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.giga_sangsue);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.glacier);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.griffe);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.griffe_acier);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.grobisou);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.grozyeux);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.guillotine);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.hate);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.hydroblast);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.hydrocanon);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.hydroqueue);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.hypnose);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.intimidation);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.jackpot);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.jet_de_pierre);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.jet_de_sable);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.koud_korne);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.lame_d_air);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.lance_flamme);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.lance_soleil);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.laser_glace);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.lechouille);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.ligotage);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.mania);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.massdos);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.mega_sangsue);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.megacorne);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.metronome);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.mimi_queue);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.mimique);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.morphing);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.morsure);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.mur_lumiere);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.onde_boreale);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.osmerang);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.ouragan);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.para_spore);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.picpic);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.pied_voltige);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.pince_masse);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.piqure);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.pistoletAO);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.plaie_croix);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.plaquage);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.poing_comete);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.poing_eclair);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.poing_feu);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.poing_glace);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.poing_karate);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.poing_ombre);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.poison_croix);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.poudre_dodo);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.poudre_toxik);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.pouv_antique);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.psychik);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.psyko);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.psykoud_boul);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.puissance);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.puredpois);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.queue_de_fer);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.rafale_psy);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.rapace);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.rayon_gemme);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.rayon_signal);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.regard_noir);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.relache);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.repli);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.repos);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.riposte);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.ronflement);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.roue_feu);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.roulade);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.rugissement);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.saumure);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.secretion);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.seisme);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.siffl_herbe);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.soin);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.souplesse);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.spore);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.stockage);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.stratopercut);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.surf);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.surpuissance);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.synthese);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.taillade);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.teleport);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.telluriforce);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.tempete_foudroyante);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.tempetesable);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.tenacite);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.tonnerre);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.torgnoles);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.tornade);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.tourniquet);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.tranch_herbe);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.tranche);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.tranche_nuit);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.trempette);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.tunnel);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.ultimapoing);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.ultralaser);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.ultrason);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.vampigraine);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.vampirisme);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.vibraqua);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.vive_attaque);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.vit_extreme);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.vol);
        this.listeDeCapacite.ajoutListeCapacite(Capacites.vol_vie);
    }

    private void creeCapacite () {
        Capacites.acide.ajouterAttribut(Attributs.defSpe, 10, false, false);
        Capacites.acidarmure.ajouterAttribut(Attributs.def, 20, true, true);
        Capacites.aile_acier.ajouterAttribut(Attributs.def, 10, true, true);
        Capacites.amnesie.ajouterAttribut(Attributs.defSpe, 20, true, true);
        Capacites.anti_brume.ajouterAttribut(Attributs.esq, 10, false, false);
        Capacites.armure.ajouterAttribut(Attributs.def, 10, true, true);
        Capacites.aromatherapi.ajouterEtat(Etat.brulure);
        Capacites.aromatherapi.ajouterEtat(Etat.folie);
        Capacites.aromatherapi.ajouterEtat(Etat.gel);
        Capacites.aromatherapi.ajouterEtat(Etat.paralise);
        Capacites.aromatherapi.ajouterEtat(Etat.poison);
        Capacites.aromatherapi.ajouterEtat(Etat.someil);
        Capacites.ball_Ombre.ajouterAttribut(Attributs.defSpe, 10, false, false);
        Capacites.boue_bombe.ajouterAttribut(Attributs.prec, 30, false, false);
        Capacites.boul_armure.ajouterAttribut(Attributs.def, 10, true, true);
        Capacites.bourdon.ajouterAttribut(Attributs.defSpe, 10, false, false);
        Capacites.brouillard.ajouterAttribut(Attributs.prec, 10, false, false);
        Capacites.bulleDo.ajouterAttribut(Attributs.vit, 10, false, false);
        Capacites.chargeur.ajouterAttribut(Attributs.defSpe, 10, true, false);
        Capacites.charme.ajouterAttribut(Attributs.att, 20, true, false);
        Capacites.close_combat.ajouterAttribut(Attributs.def, 10, false, true);
        Capacites.close_combat.ajouterAttribut(Attributs.defSpe, 10, false, true);
        Capacites.cognobidon.ajouterAttribut(Attributs.att, 60, true, false);
        Capacites.coud_boue.ajouterAttribut(Attributs.prec, 100, false, false);
        Capacites.coupdmain.ajouterAttribut(Attributs.att, 10, true, false);
        Capacites.croissance.ajouterAttribut(Attributs.attSpe, 10, true, true);
        Capacites.danse_lame.ajouterAttribut(Attributs.att, 20, true, false);
        Capacites.danse_plume.ajouterAttribut(Attributs.att, 20, false, false);
        Capacites.doux_parfum.ajouterAttribut(Attributs.esq, 20, false, false);
        Capacites.eclategriffe.ajouterAttribut(Attributs.def, 10, false, false);
        Capacites.eco_sphere.ajouterAttribut(Attributs.defSpe, 10, false, false);
        Capacites.ecume.ajouterAttribut(Attributs.vit, 10, false, false);
        Capacites.gonflette.ajouterAttribut(Attributs.att, 10, true, true);
        Capacites.gonflette.ajouterAttribut(Attributs.def, 10, true, true);
        Capacites.griffe_acier.ajouterAttribut(Attributs.att, 10, true, true);
        Capacites.grimace.ajouterAttribut(Attributs.vit, 20, false, false);
        Capacites.grincement.ajouterAttribut(Attributs.def, 20, false, false);
        Capacites.grozyeux.ajouterAttribut(Attributs.def, 10, false, false);
        Capacites.hate.ajouterAttribut(Attributs.vit, 20, true, true);
        Capacites.jet_de_sable.ajouterAttribut(Attributs.prec, 10, false, false);
        Capacites.machination.ajouterAttribut(Attributs.attSpe, 20, true, true);
        Capacites.machouille.ajouterAttribut(Attributs.def, 20, false, false);
        Capacites.malediction.ajouterAttribut(Attributs.att, 10, true, true);
        Capacites.malediction.ajouterAttribut(Attributs.def, 10, true, true);
        Capacites.malediction.ajouterAttribut(Attributs.vit, 10, false, true);
        Capacites.martopoing.ajouterAttribut(Attributs.vit, 10, false, true);
        Capacites.mimi_queue.ajouterAttribut(Attributs.def, 10, false, false);
        Capacites.mur_de_fer.ajouterAttribut(Attributs.def, 20, false, false);
        Capacites.mur_lumiere.ajouterAttribut(Attributs.defSpe, 30, true, true);
        Capacites.ocroupi.ajouterAttribut(Attributs.prec, 10, false, false);
        Capacites.octazooka.ajouterAttribut(Attributs.prec, 10, false, false);
        Capacites.onde_boreale.ajouterAttribut(Attributs.att, 10, false, false);
        Capacites.plenitude.ajouterAttribut(Attributs.attSpe, 10, true, true);
        Capacites.plenitude.ajouterAttribut(Attributs.defSpe, 10, true, true);
        Capacites.pouv_antique.ajouterAttribut(Attributs.att, 10, true, true);
        Capacites.pouv_antique.ajouterAttribut(Attributs.attSpe, 10, true, true);
        Capacites.pouv_antique.ajouterAttribut(Attributs.def, 10, true, true);
        Capacites.pouv_antique.ajouterAttribut(Attributs.defSpe, 10, true, true);
        Capacites.pouv_antique.ajouterAttribut(Attributs.esq, 10, true, true);
        Capacites.pouv_antique.ajouterAttribut(Attributs.prec, 10, true, true);
        Capacites.pouv_antique.ajouterAttribut(Attributs.vit, 10, true, true);
        Capacites.psyko.ajouterAttribut(Attributs.defSpe, 10, false, false);
        Capacites.queue_de_fer.ajouterAttribut(Attributs.def, 10, false, false);
        Capacites.reflet.ajouterAttribut(Attributs.esq, 10, true, true);
        Capacites.repli.ajouterAttribut(Attributs.def, 10, true, true);
        Capacites.repos.ajouterEtat(Etat.brulure);
        Capacites.repos.ajouterEtat(Etat.folie);
        Capacites.repos.ajouterEtat(Etat.gel);
        Capacites.repos.ajouterEtat(Etat.paralise);
        Capacites.repos.ajouterEtat(Etat.poison);
        Capacites.repos.ajouterEtat(Etat.someil);
        Capacites.reveil_force.ajouterEtat(Etat.someil);
        Capacites.rugissement.ajouterAttribut(Attributs.att, 10, false, false);
        Capacites.secretion.ajouterAttribut(Attributs.att, 10, false, false);
        Capacites.seduction.ajouterAttribut(Attributs.attSpe, 20, false, false);
        Capacites.surpuissance.ajouterAttribut(Attributs.att, 10, false, true);
        Capacites.surpuissance.ajouterAttribut(Attributs.def, 10, false, true);
        Capacites.telluriforce.ajouterAttribut(Attributs.defSpe, 10, false, false);
        Capacites.tempeteverte.ajouterAttribut(Attributs.attSpe, 10, false, true);
        Capacites.tir_de_boue.ajouterAttribut(Attributs.vit, 10, false, false);
        Capacites.vent_argente.ajouterAttribut(Attributs.att, 10, true, true);
        Capacites.vent_argente.ajouterAttribut(Attributs.attSpe, 10, true, true);
        Capacites.vent_argente.ajouterAttribut(Attributs.def, 10, true, true);
        Capacites.vent_argente.ajouterAttribut(Attributs.defSpe, 10, true, true);
        Capacites.vent_argente.ajouterAttribut(Attributs.esq, 10, true, true);
        Capacites.vent_argente.ajouterAttribut(Attributs.prec, 10, true, true);
        Capacites.vent_argente.ajouterAttribut(Attributs.vit, 10, true, true);
        Capacites.vent_arriere.ajouterAttribut(Attributs.vit, 50, true, true);
        Capacites.vent_glace.ajouterAttribut(Attributs.vit, 10, false, false);
    }

    public ListeDeCapacite getListeCapacite () {
        return this.listeDeCapacite;
    }
    
}
